In [11]:
import pandas as pd
import numpy as np

In [12]:
df = pd.DataFrame(data=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), columns=['A', 'B', 'C'])
df

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [16]:
from sklearn.preprocessing import KBinsDiscretizer
est = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='uniform').fit(df) #‘quantile’, ‘kmeans’ da deneb

In [17]:
#{‘onehot’, ‘onehot-dense’, ‘ordinal’}, (default=’onehot’) dene..
yeni = est.transform(df)
print(yeni)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]]
