# 21-09-2020

In [2]:
import numpy as np

In [14]:
vektor = np.array([1,2,3,4,5]) # vektör

In [15]:
type(vektor)

numpy.ndarray

In [16]:
vektor

array([1, 2, 3, 4, 5])

In [18]:
np.array([[1,2,3],[4,5,6]]) # 3x3'lük bir matris

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
matris = np.array([
    [1,2,3],
    [4,5,6]
])

In [21]:
matris.shape

(2, 3)

In [22]:
matris.ndim

2

In [23]:
vektor.ndim

1

In [24]:
vektor.shape

(5,)

In [26]:
matris2 = np.array([
    [7,8,9],
    [10,11,12]
])

In [28]:
matris + matris2 # matrisleri skaler olarak topluyoruz

array([[ 8, 10, 12],
       [14, 16, 18]])

In [30]:
matris * matris2 # matrisleri skaler olarak çarpıyoruz

array([[ 7, 16, 27],
       [40, 55, 72]])

In [33]:
vektor = np.array([-4,3,8])

In [38]:
np.dot(matris,vektor) # matris ile vektörü çarpıyoruz

array([26, 47])

In [39]:
matris.dot(vektor) # matris ile vektörü çarpıyoruz

array([26, 47])

In [42]:
matris.transpose() # matrisin transpozunu alıyoruz

array([[1, 4],
       [2, 5],
       [3, 6]])

In [44]:
matris.T # matrisin transpozunu alıyoruz

array([[1, 4],
       [2, 5],
       [3, 6]])

In [47]:
matris.T.shape # matrisin transpozunun boyutları

(3, 2)

In [50]:
print(f"matris'in boyutları: {matris.shape}\nmatris'in transpozunun boyutları: {matris.T.shape}")

matris'in boyutları: (2, 3)
matris'in transpozunun boyutları: (3, 2)
